# PyTorch Toutorial

## Tensor - pytorch에서 연산을 수행하기 위한 가장 기본적인 객체

In [2]:
import torch
import numpy as np

In [3]:
x = torch.Tensor( [ [ 1, 2 ], [ 3, 4 ] ] )
print( x )

tensor([[1., 2.],
        [3., 4.]])


In [4]:
x = torch.from_numpy( np.array( [ [ 1, 2 ], [ 3, 4 ] ] ) )
print( x )

tensor([[1, 2],
        [3, 4]])


In [5]:
x = np.array( [ [ 1, 2 ], [ 3, 4 ] ] )
print( x )

[[1 2]
 [3 4]]


## Autograd - 자동으로 미분 및 역전파를 수행하는 기능

In [6]:
x = torch.FloatTensor( 2, 2 )
y = torch.FloatTensor( 2, 2 )
print( x )
print( y )

tensor([[5.1489e+25, 4.5659e-41],
        [2.6274e-31, 3.0698e-41]])
tensor([[5.1489e+25, 4.5659e-41],
        [2.6270e-31, 3.0698e-41]])


In [ ]:
y.requires_grad_( True )

